version: "3.9"
services:
  app_service:
    container_name: app
    build:
      dockerfile: ./dotnet/TorteLand/TorteLand.App/Dockerfile
    ports:
      - "8080:80"

  bot_service:
    container_name: bot
    build:
      dockerfile: ./dotnet/TorteLand/TorteLand.Bot/Dockerfile
    depends_on:
      - app_service

  front_service:
    container_name: front
    build:
      dockerfile: ./angular/torteland/Dockerfile
    ports:
      - "4014:81"
    depends_on:
      - app_service